# Generated by Django 6.0.5 on 2026-05-05 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('data_nascimento', models.DateField()),
                ('endereco', models.TextField()),
                ('telefone', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
