# Generated by Django 6.0.5 on 2026-07-07 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta (Em Orçamento)'), ('EM_EXECUCAO', 'Em Execução'), ('CONCLUIDA', 'Concluída (Aguardando Pagamento)'), ('FINALIZADA', 'Finalizada e Paga'), ('CANCELADA', 'Cancelada')], default='ABERTA', max_length=20)),
                ('forma_pagamento', models.CharField(blank=True, choices=[('PIX', 'Pix'), ('DINHEIRO', 'Dinheiro'), ('CARTAO_CREDITO', 'Cartão de Crédito'), ('CARTAO_DEBITO', 'Cartão de Débito')], max_length=20, null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico', to='veiculos.veiculo')),
            ],
        ),
        migrations.CreateModel(
            name='ItemProcedimentoOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_cobrado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.procedimento')),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedimentos', to='ordens_servico.ordemservico')),
            ],
        ),
        migrations.CreateModel(
            name='ItemInsumoOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_utilizada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.insumos')),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='ordens_servico.ordemservico')),
            ],
        ),
    ]
