# Generated by Django 6.0.5 on 2026-07-07 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(error_messages={'unique': 'Já existe um procedimento cadastrado com este nome.'}, max_length=255, unique=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tempo_medio', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insumos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('marca', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('quantidade', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('nome', 'marca')},
            },
        ),
    ]
